version: '3.8'

services:
  firstday-api:
    build:
      context: .
      dockerfile: FirstDay.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=YOUR_LIGHTSAIL_POSTGRES_HOST;Database=firstday;Username=postgres;Password=YOUR_DB_PASSWORD
    restart: always

  firstday-ui:
    build:
      context: ./FirstDay.UI
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - firstday-api
    restart: always

  firstday-admin-api:
    build:
      context: .
      dockerfile: FirstDay.Admin.API/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=YOUR_LIGHTSAIL_POSTGRES_HOST;Database=firstday;Username=postgres;Password=YOUR_DB_PASSWORD
    restart: always

  firstday-admin-ui:
    build:
      context: ./FirstDay.Admin.UI
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - firstday-admin-api
    restart: always